apiVersion: v1
kind: Service
metadata:
  name: ishop-gateway-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: ishop-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081