apiVersion: apps/v1
kind: Deployment
metadata:
  name: ishop-gateway
  namespace: dev
  labels:
    app: ishop-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ishop-gateway
  template:
    metadata:
      labels:
        app: ishop-gateway
    spec:
      containers:
        - name: ishop-gateway
          image: e2rabi11/ishop-gateway:1.0.4-SNAPSHOT
          env:
            - name: ISHOP_AUTHORIZATION_SERVICE_HOST
              value: "http://192.168.65.4:30146"
          ports:
          - containerPort: 8081