apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  namespace: dev
spec:
  type: NodePort
  selector:
    app: ishop-authorization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080