
spring:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
         format_sql: true
         ddl-auto: create-drop
         dialect: org.hibernate.dialect.PostgreSQLDialect

elastic:
  hostname: 127.0.0.1:9200
grpc:
  server:
    port: 50010
springdoc:
  api-docs:
    path: /api-docs
