

elastic:
  hostname: 127.0.0.1:9200


#docker run -p 9200:9200 --name elasticsearch bitnami/elasticsearch:latest
# 137.184.244.199:9200/_cat/indices?h=index  get all indices
# 137.184.244.199:9200/product-store/_search  get all document for the index product-store