
spring:
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
         format_sql: true
         ddl-auto: update
         dialect: org.hibernate.dialect.PostgreSQLDialect
elastic:
  hostname: 127.0.0.1:9200
springdoc:
  api-docs:
    path: /api-docs

#docker run -p 9200:9200 --name elasticsearch bitnami/elasticsearch:latest
# 137.184.244.199:9200/_cat/indices?h=index  get all indices
# 137.184.244.199:9200/product-store/_search  get all document for the index product-store